import type { ListKey } from './lists';

/** Listas iniciais, extraidas da aba "Dados" de PLANILHA_DE_REGISTRO.xlsm.
 *  Apenas espacos sobrando foram removidos e a ordem alfabetica refeita; nenhum
 *  nome foi reescrito. O padrao de nomes segue como esta no original, com as
 *  inconsistencias que ja existiam la (ver README). */
export const LISTAS_INICIAIS: Record<ListKey, string[]> = {
  vtr: [
    'AA 11',
    'AA 16',
    'ABI 06',
    'AC 26',
    'AO 42',
    'AO 47',
    'AO 48',
    'AO 56',
    'AO 62',
    'AO 63',
    'AO 66',
    'APP 5',
    'APS 240',
    'APS 376',
    'APS 407',
    'APS 424',
    'ASG 188',
    'ASG 46',
    'ETIOS APAM',
    'SPIN APAM',
    'UNO APAM',
    'UR 807',
  ],
  condutor: [
    'ADEMÉSIO SGT',
    'ADIEL SGT',
    'AGATANGELO PTTC',
    'ALVES PTTC',
    'ARAGÃO SGT',
    'AURÉLIO PTTC',
    'B. FARIAS SGT',
    'BARRELA SGT',
    'C. SILVA SGT',
    'CARMONA',
    'CERQUEIRA TEN',
    'CEZAR ARRUDA ST',
    'COSTA PTTC',
    'CRISTIANO PTTC',
    'DANIEL GALVÃO SGT',
    'DIEGO APAM',
    'DINIZ TEN',
    'DISARELI ST',
    'EDNALDO PTTC',
    'EDSON SGT',
    'ELIEZER',
    'EPAMINONDAS SGT',
    'FIGUEIRA FC',
    'FILGUEIRA ST',
    'GENILSON SGT',
    'GEOVANE MAJ PTTC',
    'GILSON SGT',
    'GLEIDSON SGT',
    'GOMES PTTC',
    'GRAZIELLE SGT',
    'H. MEDEIROS SD',
    'HUMBERTO ST',
    'JANILSOM PTTC',
    'JANINI FC',
    'JARDEL SGT',
    'JORGE PTTC',
    'KELMER FC',
    'LEANDRO FC',
    'LIBERATO APAM',
    'MACIEL SGT',
    'MADUREIRA SGT',
    'MAJ DOUGLAS',
    'MALAQUIAS ST',
    'MATIAS SGT',
    'MATIOLLI',
    'MENDONÇA PTTC',
    'MICHEL AQUINO ST',
    'MIKE ST',
    'MILTON TEN',
    'NEPUCENO SGT',
    'P. SOUZA PTTC',
    'PEDROCA SGT',
    'RAIMUNDO PTTC',
    'RICARDO PTTC',
    'RODRIGO SGT',
    'ROMUALDO SGT',
    'RONALDO PTTC',
    'RONNIEVON CAP',
    'SANTANA TC',
    'SÉRGIO SGT',
    'SGT JARDELINE',
    'STEVES',
    'TOCANTINS CAP',
    'ULHOA TC',
    'VANIA ST',
    'VLADMIR PTTC',
    'WAGNER SGT',
    'ZEIDAN TEN',
  ],
};
